Task 3
sergey-berezin/401_gilyazova pull request #3
Opened 2022-11-21 14:30 UTC by alsugiliazova

2022-11-22 08:48 UTC, sergey-berezin requested changes
Надо убрать папку .vs из PR.

2022-11-22 08:48 UTC, sergey-berezin commented on task3/Class1.cs
> +            string[] splittingPath = path.Split("\\");
Лучше использовать `Path.GetFileName(...)`

2022-11-22 08:48 UTC, sergey-berezin commented on task3/MainWindow.xaml.cs
> +                throw;
Зачем ловить исключение, чтобы его снова бросить?

2022-11-22 08:48 UTC, sergey-berezin commented on task3/MainWindow.xaml.cs
> +            catch { }
Пустой `catch` скроет все ошибки. Это то, что вы хотите?

2022-11-22 09:43 UTC, alsugiliazova commented
Я исправила ошибки, про которые Вы написали

2022-11-28 13:23 UTC, alsugiliazova commented
Удалила папку .vs

2022-12-02 08:26 UTC, merged